DROP DATABASE IF EXISTS blogdb;
CREATE DATABASE IF NOT EXISTS blogdb;

DROP DATABASE IF EXISTS userdb;
CREATE DATABASE IF NOT EXISTS userdb;

DROP DATABASE IF EXISTS sonarqubedb;
CREATE DATABASE IF NOT EXISTS sonarqubedb;