services:
  app:
    build: .
    container_name: blog-api
    restart: on-failure
    ports:
      - "8081:8080"
    networks:
      - blog-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/blogdb
    depends_on:
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:8.1
    container_name: mysql
    ports:
      - "3307:3306"
    networks:
      - blog-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blogdb
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-data-volume:/var/lib/mysql

volumes:
  mysql-data-volume:

networks:
  blog-network:


