services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - blog-network
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy

  blog-service:
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    container_name: blog-service
    restart: on-failure
    ports:
      - "8082:8082"
    networks:
      - blog-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blogdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_healthy

  mysql:
    image: mysql:8.1
    container_name: mysql
    ports:
      - "3307:3306"
    networks:
      - blog-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    volumes:
      - ./user-service/src/main/resources/scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
      - mysql-data-volume:/var/lib/mysql

  postgres:
    image: postgres:15
    container_name: postgres
    networks:
    - blog-network
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sonardb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonar" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:9-community
    container_name: sonarqube
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9000:9000"
    networks:
      - blog-network
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonardb
      SONAR_JDBC_USERNAME: ${SONAR_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
      - sonarqube_config:/opt/sonarqube/conf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - blog-network
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail http://localhost:9200" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.24
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - blog-network
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  eurekaserver:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: on-failure
    networks:
      - blog-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - '9094:9094'
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - blog-network
    healthcheck:

      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8090:8080'
    depends_on:
      kafka:
        condition: service_healthy
    environment:
       KAFKA_CLUSTERS_0_NAME: local
       KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - blog-network

volumes:
  mysql-data-volume:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonarqube_config:
  elasticsearch-data-volume:
  postgres-data:

networks:
  blog-network:
    driver: bridge